name: Cherry-pick and Squash Commits

on:
  repository_dispatch:
    types: [event-triggered-by-jira]
    


jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  cherry-pick-and-squash-commits:
    uses: Rudra-tech17/ticket-automation/.github/workflows/auto.yml@main
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      event-type: cherry-pick-triggered
      client-payload: '{"jira-issue":"${{ github.event.client_payload.jira-issue }}"}'
