name: Cherry-pick and Squash Commits

on:
  repository_dispatch:
    types: [event-triggered-by-jira]

jobs:
  cherry-pick-and-squash-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cherry-pick Workflow
        uses: Rudra-tech17/ticket-automation/.github/workflows/auto.yml@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: cherry-pick-triggered
          client-payload: '{"jira-issue":"${{ github.event.client_payload.jira-issue }}"}'
